import TicTacToeGame from '../scripts/TicTacToeGame.js';
const X_CLASS = 'x';
const O_CLASS = 'o';
const cellElements = document.querySelectorAll('[data-cell]');
const board = document.getElementById('gameboard');
const endMessage = document.querySelector('[data-end-message]');
const endText = document.querySelector('[data-end-text]');
const restartButton = (document.querySelector('[data-restart-button]'));
const singlePlayerButton = (document.getElementById('single-button'));
const multiPlayerButton = (document.getElementById('multi-button'));
const aiButton = document.getElementById('ai-button');
const ticTacToe = new TicTacToeGame(cellElements, board, endMessage, endText, restartButton, [singlePlayerButton, multiPlayerButton, aiButton]);
ticTacToe.startGame();
